class Selectors

    USERNAME = "user-name"
    PASSSWORD = "password"
    LOGINBUTTON = "login-button"
    HOMEPAGETITLE = "app_logo"
    ERRORMESSAGE = ".error-message-container.error h3"
    MENU = "react-burger-menu-btn"
    LOGOUTBUTTON = "logout_sidebar_link"
    LOGINPAGETITLE = "login_logo"
    PRODUCTLIST = "inventory_item_name"
    ADDTOCART = "button[data-test]"
    CART = "shopping_cart_link"
    CHECKOUT = "checkout"
    FIRSTNAME = "first-name"
    LASTNAME = "last-name"
    ZIPCODE = "postal-code"
    CONTINUEBUTTON = "continue"
    FINISHBUTTON = "finish"
    CHECKOUTBANNER = "complete-header"
    PRICELIST = "inventory_item_price"
    PRODUCTSORT = "product_sort_container"
    ITEMNUMBERINCART = "shopping_cart_badge"
    PRODUCTBACKPACK = "button[name*=sauce-labs-backpack]"
    PRODUCTBIKELIGHT = "button[name*=sauce-labs-bike-light]"
    PRODUCTTSHIRT = "button[name*=sauce-labs-bolt-t-shirt]"
    PRODUCTJACKET = "button[name*=sauce-labs-fleece-jacket]"
    PRODUCTONESIE = "button[name*=sauce-labs-onesie]"
    PRODUCTTSHIRTRED = "button[name*=allthethings]"
    SUBTOTAL = "summary_subtotal_label"
    TAXCALCULATED = "summary_tax_label"
    FULLTOTAL = "div[class*=summary_total_label]"
    FOOTER = "footer"
    FOOTER_TWITTER = "social_twitter a"
    FOOTER_FB = "social_facebook a"
    FOOTER_LINKEDIN = "social_linkedin a"

end